# Generated by Django 5.2 on 2025-04-07 09:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tvs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_damage', models.TextField(verbose_name='Initial Damage Description')),
                ('the_date', models.DateTimeField(auto_now_add=True, verbose_name='Reception Date')),
                ('initial_tax', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Initial Service Fee')),
                ('returned', models.BooleanField(default=False, verbose_name='Device Returned?')),
                ('case_number', models.CharField(max_length=255, unique=True)),
                ('photos', models.ImageField(upload_to='receptions/%Y/%m/%d/')),
                ('in_guarantee', models.BooleanField(default=False, verbose_name='Under Guarantee?')),
                ('have_guarantee', models.BooleanField(default=False, verbose_name='Has Guarantee?')),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_check', 'In Check'), ('check_feedback', 'Check Feedback'), ('calling_customer', 'Calling Customer'), ('wait_in_reception', 'Wait in Reception'), ('in_maintenance', 'In Maintenance'), ('given_to_customer', 'Given to Customer'), ('refused_or_not_accept', 'Refused or Not Accept')], default='received', max_length=50, verbose_name='Repair Status')),
                ('eng_name', models.CharField(blank=True, max_length=255, verbose_name='Engineer Name')),
                ('damage', models.CharField(blank=True, max_length=255, verbose_name='Actual Damage Found')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Repair Cost')),
                ('maintenance_date', models.DateTimeField(blank=True, null=True, verbose_name='Maintenance Date')),
                ('who_receive_it', models.CharField(blank=True, max_length=255, verbose_name='Received By')),
                ('current_place', models.CharField(blank=True, max_length=255, verbose_name='Current Location')),
                ('the_time', models.DateTimeField(blank=True, null=True, verbose_name='Completion Time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='customers.customer')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_receptions', to=settings.AUTH_USER_MODEL)),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to='tvs.tv')),
            ],
            options={
                'verbose_name': 'Device Reception',
                'verbose_name_plural': 'Device Receptions',
                'ordering': ['-the_date'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('confirm_maintenance', 'Confirm Maintenance'), ('pickup_device', 'Call to Pick Up Device')], max_length=50)),
                ('summary', models.TextField(verbose_name='Call Summary')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='reception.reception')),
            ],
            options={
                'verbose_name': 'Service Call',
                'verbose_name_plural': 'Service Calls',
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='TvAttatchment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='attachments/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, verbose_name='Attachment Description')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reception.reception')),
            ],
            options={
                'verbose_name': 'TV Attachment',
                'verbose_name_plural': 'TV Attachments',
            },
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['status'], name='reception_r_status_046c96_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['customer'], name='reception_r_custome_114bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='reception',
            index=models.Index(fields=['case_number'], name='reception_r_case_nu_e7c960_idx'),
        ),
    ]
