# Generated by Django 5.2 on 2025-04-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_receptionphoto_repairnote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionphoto',
            options={'ordering': ['-id'], 'verbose_name': 'Reception Photo', 'verbose_name_plural': 'Reception Photos'},
        ),
        migrations.RemoveField(
            model_name='call',
            name='successful',
        ),
        migrations.RemoveField(
            model_name='receptionphoto',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='repairnote',
            name='is_internal',
        ),
        migrations.AddField(
            model_name='receptionphoto',
            name='reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reception.reception'),
        ),
    ]
