# Generated by Django 5.2 on 2025-04-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('OUT', 'Checked Out'), ('REPAIR', 'In Repair')], default='IN_STOCK', max_length=10),
        ),
    ]
